spring:
    data:
        elasticsearch:
            cluster-nodes: localhost:9300
            repositories:
                enabled: true
mm:
    proxy:
        set_proxy: false
        url: connsvr.nike.com
        port: 8080
    encrypt:
        password: Password123